name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Build the Docker image
      env:  
       ENV_FILE: ${{secrets.ENVIRONMENT_FILE}}
      run: |
       touch .env
       cat $ENV_FILE > .env
       docker build . --tag felobetter/teswp2:latest
      
    - name: Docker Push
      run: docker push felobetter/teswp2
